fixed_frame: "base_link"
object_frame: "reach_object"
results_directory: "$(find reach_demo)/results"
pcd_filename: "$(find reach_demo)/config/part.pcd"
get_avg_neighbor_count: false
compare_dbs: []
visualize_results: true

optimization:
  radius: 0.2
  max_steps: 10
  step_improvement_threshold: 0.01

ik_solver_config:
  name: "moveit_reach_plugins/ik/MoveItIKSolver"
  distance_threshold: 0.0
  planning_group: "manipulator"
  collision_mesh_filename: "package://reach_demo/config/part.ply"
  collision_mesh_frame: "reach_object"
  touch_links: []
  evaluation_plugin:
    name: "reach_core/plugins/MultiplicativeFactory"
    plugins:
      - name: "moveit_reach_plugins/evaluation/ManipulabilityMoveIt"
        planning_group: "manipulator"
      - name: "moveit_reach_plugins/evaluation/DistancePenaltyMoveIt"
        planning_group: "manipulator"
        distance_threshold: 0.025
        exponent: 2
        collision_mesh_filename: "package://reach_demo/config/part.ply"
        collision_mesh_frame: "reach_object"
        touch_links: []

display_config:
  name: "moveit_reach_plugins/display/MoveItReachDisplay"
  planning_group: "manipulator"
  collision_mesh_filename: "package://reach_demo/config/part.ply"
  collision_mesh_frame: "reach_object"
  fixed_frame: "base_link"
  marker_scale: 0.05
